### PR TITLE
Added FAQs (from webinar) and changed the taxId to tax number

### PR DESCRIPTION
**Pull request by saschaknapp**
Added FAQs (from webinar) and changed the taxId to tax number

### CODE REVIEW

**Review by Bluette-C-Riviere — APPROVED** [review]

**Comment by saschaknapp** [comment]
Hi @TSchmiedlechner , can you check why the check failed? Seems like this blocks the change from being visible in the docs :(

**Comment by TSchmiedlechner** [comment]
@saschaknapp fixed, looks like the latest version of the markdown link checker requires Node.JS v20

**Comment by saschaknapp** [comment]
Seems like it still didn't get imported into the docs :( Can you check again @TSchmiedlechner ?

**Comment by TSchmiedlechner** [comment]
There was a whitespace in the path 🥲`i18n /...` - the build now seems to be running:
https://dev.azure.com/fiskaltrust/fiskaltrust/_build/results?buildId=76257&view=results

**Comment by saschaknapp** [comment]
Now the German version is not shown anymore and the FAQs still not included. Looks like the portal doesn't like Mondays. @TSchmiedlechner :D

**Comment by TSchmiedlechner** [comment]
Hey, the build is still failing, yep :( i will have to check this in the evening, seems pretty weird to me on first sight

**Comment by TSchmiedlechner** [comment]
Hey again @saschaknapp , it's working now - I had overlooked that the Docusaurus build moves the i18n things around quite a bit.

**Comment by saschaknapp** [comment]
Hi @TSchmiedlechner, thank you for checking this. I don't know how to say this, but it's still/again not visible :/

**Pull request merged**
